language: node_js
node_js:
- '0.10'
env:
  matrix:
  - JOB=test
  global:
  - LOGS_DIR=logs
  - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
  - secure: "UzS30X6P3x3UWfAFNmGNv00oJimc3soCgK3n4qULEFoy6dzMo7qe+p3KDV99dZ9IKtZUzqFOp7tb2EWdu67alel1t/ftoK0X71u/S26Pyx95PeQnnKRr4GlcTYWFaflQvmYqyI6iu58/e8MvgSs/kbHpdiwA3FXcjEXxSsDlZfg="
  - secure: "e0sxpyBeP/jIHPtPyf3pTCTWr0Llx1D2fU6YYAh82OvMwX5nLH5oYAVAsAto8Mzvi2Nf9+CWOouU+kNCaeeKXxn6geW3cRWNNd035T5/vlR8Bbm6Ad9FS0W/OYZzQPAclUa6qX0d5hxrLYba0m/P+FhPKc9hxiaP2GSsqDWtTK4="
install:
- npm install protractor
- npm install httpster
before_script:
- mkdir -p $LOGS_DIR
- curl https://raw.githubusercontent.com/William-Olson/SauceTest/master/scripts/sauce_connect.sh | bash

script:
- protractor ./test/protractor.conf.js
after_script:
- ./scripts/print_logs.sh
